# Explore and clean data

### Data Exploration
Haremos una breve exploración para tener una mejor idea de lo que contiene nuestro conjunto de datos; esto nos dará una mejor idea de cómo procesar los datos.

Lo primero que vamos a hacer es llamar al método **info()** en nuestro DataFrame de pandas; esto imprimirá un resumen conciso de los datos del vino contenidos en el DataFrame. Después de ejecutar esta celda, aprenderá:
- Los datos contienen 178 muestras de datos.
- Hay 14 columnas en total, incluida la columna de destino (lo que queremos predecir)
- Hay 0 columnas con valores faltantes; puede inferir esto de la columna "Recuento no nulo".
- Todas las funciones son del tipo de datos float64, mientras que la etiqueta de destino es int64.
- Los datos utilizan 19,6 KB de memoria.

In [57]:
import pandas as pd
import numpy as np
from sklearn import datasets
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

wine_data = datasets.load_wine() 

# Convert data to pandas dataframe
wine_df = pd.DataFrame(wine_data.data, columns=wine_data.feature_names)

# Add the target label
wine_df["target"] = wine_data.target

In [41]:
wine_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 178 entries, 0 to 177
Data columns (total 14 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   alcohol                       178 non-null    float64
 1   malic_acid                    178 non-null    float64
 2   ash                           178 non-null    float64
 3   alcalinity_of_ash             178 non-null    float64
 4   magnesium                     178 non-null    float64
 5   total_phenols                 178 non-null    float64
 6   flavanoids                    178 non-null    float64
 7   nonflavanoid_phenols          178 non-null    float64
 8   proanthocyanins               178 non-null    float64
 9   color_intensity               178 non-null    float64
 10  hue                           178 non-null    float64
 11  od280/od315_of_diluted_wines  178 non-null    float64
 12  proline                       178 non-null    float64
 13  target                        178 non-null    int64
dtypes: float64(13), int64(1)
memory usage: 19.6 KB

**Describing the data**

Puede utilizar la función **describe()** para obtener varias estadísticas resumidas que excluyen los valores NaN sobre cada caracteristica del conjunto de datos.

In [42]:
wine_df.describe()

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280/od315_of_diluted_wines,proline,target
count,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000
mean,13.000618,2.336348,2.366517,19.494944,99.741573,2.295112,2.029270,0.361854,1.590899,5.058090,0.957449,2.611685,746.893258,0.938202
std,0.811827,1.117146,0.274344,3.339564,14.282484,0.625851,0.998859,0.124453,0.572359,2.318286,0.228572,0.709990,314.907474,0.775035
min,11.030000,0.740000,1.360000,10.600000,70.000000,0.980000,0.340000,0.130000,0.410000,1.280000,0.480000,1.270000,278.000000,0.000000
25%,12.362500,1.602500,2.210000,17.200000,88.000000,1.742500,1.205000,0.270000,1.250000,3.220000,0.782500,1.937500,500.500000,0.000000
50%,13.050000,1.865000,2.360000,19.500000,98.000000,2.355000,2.135000,0.340000,1.555000,4.690000,0.965000,2.780000,673.500000,1.000000
75%,13.677500,3.082500,2.557500,21.500000,107.000000,2.800000,2.875000,0.437500,1.950000,6.200000,1.120000,3.170000,985.000000,2.000000
max,14.830000,5.800000,3.230000,30.000000,162.000000,3.880000,5.080000,0.660000,3.580000,13.000000,1.710000,4.000000,1680.000000,2.000000

También desea tener una idea del tipo de valores que se mantienen en cada característica. La forma más rápida de aprender esto es usar el método **head()** para mostrar las primeras cinco filas de datos o el método **tail()** para ver las últimas cinco filas de datos.

In [43]:
wine_df.head()

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280/od315_of_diluted_wines,proline,target
0,14.23,1.71,2.43,15.6,127.0,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065.0,0
1,13.20,1.78,2.14,11.2,100.0,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050.0,0
2,13.16,2.36,2.67,18.6,101.0,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185.0,0
3,14.37,1.95,2.50,16.8,113.0,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480.0,0
4,13.24,2.59,2.87,21.0,118.0,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735.0,0

### Data Preprocessing

El procesamiento de datos es un paso vital en el flujo de trabajo del aprendizaje automático porque los datos del mundo real son confusos. Puede contener:  
- valores faltantes (Missing values)
- Valores redundantes (Redundant values)
- Valores atípicos (Outliers)
- Errores (Errors)
- Ruido (Noise)

Debe abordar todo esto antes de introducir los datos en un modelo de machine learning. De lo contrario, el modelo incorporará estos errores en su función de aproximación.

Aparte de que nuestros datos están en diferentes escalas, para combatir este problema, estandaricemos las funciones utilizando la clase [StandardScaler](regression/examples/scikit_learn_standard_scaler.ipynb) de sklearn. Divide por la desviación típica de cada característica, asegurándose de que las características tienen una media de 0 y una desviación típica de 1, con esto conseguiremos que todas las características están en la misma escala, lo que facilita a los algoritmos de aprendizaje automático el tratamiento eficaz de los datos.

In [54]:
# Split data into features and label 
x = wine_df[wine_data.feature_names].copy()
y = wine_df["target"].copy() 

# Instantiate scaler and fit on features
scaler = StandardScaler()
scaler.fit(x.values)

# Transform features
x_scaler = scaler.transform(x.values)

# Convert data to pandas dataframe
df_scaler = pd.DataFrame(np.round(x_scaler, 2), columns=x.columns)
x.describe()

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280/od315_of_diluted_wines,proline
count,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000
mean,13.000618,2.336348,2.366517,19.494944,99.741573,2.295112,2.029270,0.361854,1.590899,5.058090,0.957449,2.611685,746.893258
std,0.811827,1.117146,0.274344,3.339564,14.282484,0.625851,0.998859,0.124453,0.572359,2.318286,0.228572,0.709990,314.907474
min,11.030000,0.740000,1.360000,10.600000,70.000000,0.980000,0.340000,0.130000,0.410000,1.280000,0.480000,1.270000,278.000000
25%,12.362500,1.602500,2.210000,17.200000,88.000000,1.742500,1.205000,0.270000,1.250000,3.220000,0.782500,1.937500,500.500000
50%,13.050000,1.865000,2.360000,19.500000,98.000000,2.355000,2.135000,0.340000,1.555000,4.690000,0.965000,2.780000,673.500000
75%,13.677500,3.082500,2.557500,21.500000,107.000000,2.800000,2.875000,0.437500,1.950000,6.200000,1.120000,3.170000,985.000000
max,14.830000,5.800000,3.230000,30.000000,162.000000,3.880000,5.080000,0.660000,3.580000,13.000000,1.710000,4.000000,1680.000000

In [55]:
df_scaler.describe()

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280/od315_of_diluted_wines,proline
count,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,1.780000e+02,178.000000,178.000000,178.000000
mean,-0.000225,0.000281,0.000225,-0.001517,0.001067,0.000955,-0.000112,-0.000112,0.000056,4.989766e-18,-0.000056,-0.000393,-0.000169
std,1.003369,1.002726,1.002934,1.001869,1.002108,1.002647,1.002258,1.002359,1.002950,1.002696e+00,1.002786,1.003162,1.002884
min,-2.430000,-1.430000,-3.680000,-2.670000,-2.090000,-2.110000,-1.700000,-1.870000,-2.070000,-1.630000e+00,-2.090000,-1.900000,-1.490000
25%,-0.787500,-0.657500,-0.570000,-0.690000,-0.820000,-0.885000,-0.825000,-0.740000,-0.600000,-7.950000e-01,-0.767500,-0.950000,-0.787500
50%,0.060000,-0.425000,-0.020000,0.000000,-0.120000,0.095000,0.105000,-0.180000,-0.060000,-1.550000e-01,0.035000,0.240000,-0.235000
75%,0.837500,0.672500,0.700000,0.600000,0.510000,0.810000,0.845000,0.610000,0.630000,4.900000e-01,0.710000,0.790000,0.760000
max,2.260000,3.110000,3.160000,3.150000,4.370000,2.540000,3.060000,2.400000,3.490000,3.440000e+00,3.300000,1.960000,2.970000

### Model Training

Antes de que un modelo de aprendizaje automático pueda hacer predicciones, debe entrenarse con un conjunto de datos para aprender una función de aproximación.

Pero, ¿cómo sabremos si el modelo funciona bien con datos que no ha visto antes? No lo haremos a menos que lo probemos.

Hay varias formas de dividir datos en conjuntos de entrenamiento y prueba, pero scikit-learn tiene una función incorporada para hacer esto en nuestro nombre llamada **train_test_split()**

Usaremos esta función para dividir nuestros datos de modo que el 70% se use para entrenar el modelo y el 30% se use para evaluar la capacidad del modelo para generalizar a instancias invisibles.

In [58]:
# Split data into train and test
x_train_scaler, x_test_scaler, y_train, y_test = train_test_split(x_scaler, y, test_size=.3, random_state=42)

print(f"Train size:\n{round(len(x_train_scaler) / len(x) * 100)}")
print(f"Test size:\n{round(len(x_test_scaler) / len(x) * 100)}")

Train size:
70
Test size:
30

### Building the model

Gracias a sklearn, construir un modelo de aprendizaje automático es extremadamente sencillo.  Vamos a construir tres modelos para predecir la clase de vino:
- Logistic regression
- Support vector machine 
- Decision tree classifier